name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - name: Left Part
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_left.*
          template: classic
      - name: Right Part
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_right.*
          base: ""
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_skipped: blog
          plugin_languages_ignored: lua
          plugin_notable: yes
          plugin_notable_repositories: yes
