name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps: 
      - name: Left Part
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_left.*
          template: classic
          repositories_forks: yes
          base_indepth: yes
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_skipped: dotfiles, blog

      - name: Right Part
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_right.*
          base:
          repositories_forks: yes
          plugin_languages: yes
          plugin_languages_skipped: blog
          plugin_languages_ignored: lua
          plugin_languages_other: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_activity: yes
          plugin_activity_filter: issue, pr
